name: FOSSA CLI Analysis - Ruby
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  fossa_ruby:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
      ORG: ${{ github.repository_owner }}
      REPO: ${{ github.repository }}
      CUSTOM_PROPS_PAT: ${{ secrets.FOSSA_PAT }}
      HAS_FOSSA_TARGETS: ""
      FOSSA_ANALYZE_RESULT: ""

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - id: fossa-cli
        if: ${{ env.FOSSA_API_KEY != '' }}
        uses: newrelic-csec/.github/.github/composite/fossa-composite@reusable
