name: FOSSA CLI Analysis - Scala
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  check_env:
    uses: newrelic-csec/.github/.github/workflows/fossa-check-env.yml@reusable

  fossa:
    needs: check_env
    if: ${{ needs.check_env.outputs.HAS_FOSSA_API_KEY == 'true' }}
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
      ORG: ${{ github.repository_owner }}
      REPO: ${{ github.repository }}
      CUSTOM_PROPS_PAT: ${{ secrets.FOSSA_PAT }}
      HAS_FOSSA_TARGETS: ""
      FOSSA_ANALYZE_RESULT: ""

    steps:
      - uses: actions/checkout@v3
      - name: Download newrelic.jar
        if: ${{ github.repository == 'newrelic/newrelic-java-examples' }}
        run: |
          mkdir newrelic-java-agent/scala/segment-api-synchronous/libs
          curl https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic.jar --output newrelic-java-agent/scala/segment-api-synchronous/libs/newrelic.jar
      - id: fossa-cli
        uses: newrelic-csec/.github/.github/composite/fossa-composite@reusable
